// Types and comprehensive mock data for Operations Monitoring

export interface OrgTreeNode {
  id: string;
  name: string;
  code: string;
  level: 1 | 2 | 3;
  type: 'head' | 'branch' | 'department' | 'grid_station';
  industry: string;
  region: string;
  leader: string;
  leaderPhone: string;
  statusType: '正式' | '试用';
  totalPersonnel: number;
  activePersonnel: number;
  qrLimit: number;
  qrUsed: number;
  todayReports: number;
  totalReports: number;
  pendingReview: number;
  reviewedToday: number;
  passRate: number; // percentage, e.g. 96.5
  avgReviewMinutes: number;
  healthStatus: 'healthy' | 'warning' | 'busy' | 'alert';
  children?: OrgTreeNode[];
}

export interface PersonnelItem {
  id: string;
  name: string;
  avatarColor: string;
  role: '首席采编员' | '网格速报员' | '初审专员' | '终审主管' | '系统管理员' | '网安特派员';
  institutionId: string;
  institutionName: string;
  subBranchName: string;
  phone: string;
  todayReports: number;
  totalReports: number;
  todayReviewed: number;
  passRate: number;
  avgResponseMins: number;
  status: 'online' | 'busy' | 'offline';
  lastActive: string;
}

export interface ReportReviewEvent {
  id: string;
  title: string;
  category: '舆情快报' | '政务发布' | '网格巡查' | '应急速报' | '不良举报' | '重大事件';
  urgency: '高' | '中' | '普通';
  institutionName: string;
  subBranchName: string;
  reporterName: string;
  reporterRole: string;
  reviewerName?: string;
  status: 'pending_first' | 'pending_final' | 'approved' | 'rejected' | 'timeout';
  reportTime: string;
  reviewTime?: string;
  durationMins?: number;
  score?: number;
  rejectReason?: string;
}

// 18 Platform Institutions with hierarchical org tree
export const mockPlatformOrgTreeData: OrgTreeNode[] = [
  {
    id: 'INST-05',
    name: '随州市网信中心（随州市网络安全应急指挥中心）',
    code: 'SZ-WX-001',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '湖北/随州市',
    leader: '廖伟',
    leaderPhone: '189****4954',
    statusType: '正式',
    totalPersonnel: 248,
    activePersonnel: 198,
    qrLimit: 280,
    qrUsed: 248,
    todayReports: 142,
    totalReports: 14280,
    pendingReview: 8,
    reviewedToday: 134,
    passRate: 96.2,
    avgReviewMinutes: 11.5,
    healthStatus: 'healthy',
    children: [
      {
        id: 'SZ-01',
        name: '曾都区融媒体中心网络采编部',
        code: 'SZ-ZD-01',
        level: 2,
        type: 'branch',
        industry: '融媒体中心',
        region: '随州/曾都区',
        leader: '刘晓丽',
        leaderPhone: '139****8832',
        statusType: '正式',
        totalPersonnel: 64,
        activePersonnel: 56,
        qrLimit: 75,
        qrUsed: 64,
        todayReports: 46,
        totalReports: 4120,
        pendingReview: 2,
        reviewedToday: 44,
        passRate: 97.8,
        avgReviewMinutes: 9.8,
        healthStatus: 'healthy',
        children: [
          {
            id: 'SZ-01-01',
            name: '南郊街道网格化速报工作站',
            code: 'SZ-ZD-G01',
            level: 3,
            type: 'grid_station',
            industry: '网格工作站',
            region: '曾都区/南郊',
            leader: '陈思齐',
            leaderPhone: '135****4423',
            statusType: '正式',
            totalPersonnel: 22,
            activePersonnel: 19,
            qrLimit: 25,
            qrUsed: 22,
            todayReports: 18,
            totalReports: 1540,
            pendingReview: 1,
            reviewedToday: 17,
            passRate: 98.2,
            avgReviewMinutes: 8.4,
            healthStatus: 'healthy',
          },
          {
            id: 'SZ-01-02',
            name: '北郊政务新媒体采编特派室',
            code: 'SZ-ZD-G02',
            level: 3,
            type: 'grid_station',
            industry: '采编工作室',
            region: '曾都区/北郊',
            leader: '黄海波',
            leaderPhone: '186****7719',
            statusType: '正式',
            totalPersonnel: 18,
            activePersonnel: 16,
            qrLimit: 20,
            qrUsed: 18,
            todayReports: 14,
            totalReports: 1220,
            pendingReview: 0,
            reviewedToday: 14,
            passRate: 96.5,
            avgReviewMinutes: 10.2,
            healthStatus: 'healthy',
          },
        ],
      },
      {
        id: 'SZ-02',
        name: '广水市网信办融媒指挥分中心',
        code: 'SZ-GS-02',
        level: 2,
        type: 'branch',
        industry: '网信部门',
        region: '随州/广水市',
        leader: '张建国',
        leaderPhone: '137****9012',
        statusType: '正式',
        totalPersonnel: 72,
        activePersonnel: 58,
        qrLimit: 85,
        qrUsed: 72,
        todayReports: 52,
        totalReports: 4890,
        pendingReview: 4,
        reviewedToday: 48,
        passRate: 95.4,
        avgReviewMinutes: 13.2,
        healthStatus: 'busy',
        children: [
          {
            id: 'SZ-02-01',
            name: '应山街道网络舆情前哨观察站',
            code: 'SZ-GS-G01',
            level: 3,
            type: 'grid_station',
            industry: '网格工作站',
            region: '广水市/应山',
            leader: '李梦瑶',
            leaderPhone: '150****2234',
            statusType: '正式',
            totalPersonnel: 26,
            activePersonnel: 21,
            qrLimit: 30,
            qrUsed: 26,
            todayReports: 22,
            totalReports: 2130,
            pendingReview: 2,
            reviewedToday: 20,
            passRate: 94.8,
            avgReviewMinutes: 12.0,
            healthStatus: 'healthy',
          },
        ],
      },
      {
        id: 'SZ-03',
        name: '随县网络安全速报与应急处突分队',
        code: 'SZ-SX-03',
        level: 2,
        type: 'branch',
        industry: '应急处突',
        region: '随州/随县',
        leader: '王俊杰',
        leaderPhone: '138****5621',
        statusType: '正式',
        totalPersonnel: 68,
        activePersonnel: 54,
        qrLimit: 75,
        qrUsed: 68,
        todayReports: 34,
        totalReports: 3820,
        pendingReview: 1,
        reviewedToday: 33,
        passRate: 96.0,
        avgReviewMinutes: 10.8,
        healthStatus: 'healthy',
      },
      {
        id: 'SZ-04',
        name: '大洪山风景名胜区网信联络站',
        code: 'SZ-DHS-04',
        level: 2,
        type: 'department',
        industry: '文旅网信',
        region: '随州/大洪山',
        leader: '赵宏图',
        leaderPhone: '188****6651',
        statusType: '正式',
        totalPersonnel: 24,
        activePersonnel: 18,
        qrLimit: 30,
        qrUsed: 24,
        todayReports: 10,
        totalReports: 1450,
        pendingReview: 1,
        reviewedToday: 9,
        passRate: 98.0,
        avgReviewMinutes: 9.0,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-01',
    name: '国网河南省电力公司商丘供电公司',
    code: 'GW-SQ-002',
    level: 1,
    type: 'head',
    industry: '电力能源',
    region: '河南/商丘市',
    leader: '李鹏飞',
    leaderPhone: '187****8601',
    statusType: '正式',
    totalPersonnel: 310,
    activePersonnel: 246,
    qrLimit: 350,
    qrUsed: 310,
    todayReports: 168,
    totalReports: 18920,
    pendingReview: 9,
    reviewedToday: 159,
    passRate: 95.8,
    avgReviewMinutes: 14.2,
    healthStatus: 'healthy',
    children: [
      {
        id: 'GW-SQ-01',
        name: '梁园区电力安全与融媒通讯部',
        code: 'GW-LY-01',
        level: 2,
        type: 'branch',
        industry: '电力安全',
        region: '商丘/梁园区',
        leader: '程明轩',
        leaderPhone: '136****2211',
        statusType: '正式',
        totalPersonnel: 98,
        activePersonnel: 82,
        qrLimit: 110,
        qrUsed: 98,
        todayReports: 58,
        totalReports: 6240,
        pendingReview: 3,
        reviewedToday: 55,
        passRate: 96.4,
        avgReviewMinutes: 12.6,
        healthStatus: 'healthy',
      },
      {
        id: 'GW-SQ-02',
        name: '睢阳区供电应急速报网格站',
        code: 'GW-SY-02',
        level: 2,
        type: 'branch',
        industry: '电力网格',
        region: '商丘/睢阳区',
        leader: '孙宝玉',
        leaderPhone: '139****7765',
        statusType: '正式',
        totalPersonnel: 112,
        activePersonnel: 88,
        qrLimit: 125,
        qrUsed: 112,
        todayReports: 64,
        totalReports: 7120,
        pendingReview: 4,
        reviewedToday: 60,
        passRate: 95.2,
        avgReviewMinutes: 15.0,
        healthStatus: 'busy',
      },
      {
        id: 'GW-SQ-03',
        name: '永城市电力融媒工作站',
        code: 'GW-YC-03',
        level: 2,
        type: 'branch',
        industry: '县级供电',
        region: '商丘/永城市',
        leader: '郭子仪',
        leaderPhone: '158****9944',
        statusType: '正式',
        totalPersonnel: 100,
        activePersonnel: 76,
        qrLimit: 115,
        qrUsed: 100,
        todayReports: 46,
        totalReports: 5560,
        pendingReview: 2,
        reviewedToday: 44,
        passRate: 96.0,
        avgReviewMinutes: 13.8,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-04',
    name: '中共佛山市委网络安全和信息化委员会办公室',
    code: 'FS-WX-003',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '广东/佛山市',
    leader: '李学坚',
    leaderPhone: '186****8245',
    statusType: '试用',
    totalPersonnel: 420,
    activePersonnel: 352,
    qrLimit: 480,
    qrUsed: 420,
    todayReports: 215,
    totalReports: 24650,
    pendingReview: 14,
    reviewedToday: 201,
    passRate: 94.2,
    avgReviewMinutes: 16.5,
    healthStatus: 'busy',
    children: [
      {
        id: 'FS-01',
        name: '禅城区融媒体网信直报中心',
        code: 'FS-CC-01',
        level: 2,
        type: 'branch',
        industry: '融媒体中心',
        region: '佛山/禅城区',
        leader: '何伟强',
        leaderPhone: '137****3310',
        statusType: '试用',
        totalPersonnel: 130,
        activePersonnel: 110,
        qrLimit: 150,
        qrUsed: 130,
        todayReports: 78,
        totalReports: 8900,
        pendingReview: 5,
        reviewedToday: 73,
        passRate: 94.8,
        avgReviewMinutes: 15.2,
        healthStatus: 'busy',
      },
      {
        id: 'FS-02',
        name: '南海区网络安全与舆情应急中心',
        code: 'FS-NH-02',
        level: 2,
        type: 'branch',
        industry: '网络安全',
        region: '佛山/南海区',
        leader: '梁志锋',
        leaderPhone: '138****4422',
        statusType: '试用',
        totalPersonnel: 165,
        activePersonnel: 140,
        qrLimit: 190,
        qrUsed: 165,
        todayReports: 84,
        totalReports: 9650,
        pendingReview: 6,
        reviewedToday: 78,
        passRate: 93.6,
        avgReviewMinutes: 18.0,
        healthStatus: 'alert',
      },
      {
        id: 'FS-03',
        name: '顺德区网信快报与民情调查站',
        code: 'FS-SD-03',
        level: 2,
        type: 'branch',
        industry: '民情调查',
        region: '佛山/顺德区',
        leader: '陈嘉玲',
        leaderPhone: '135****8809',
        statusType: '试用',
        totalPersonnel: 125,
        activePersonnel: 102,
        qrLimit: 140,
        qrUsed: 125,
        todayReports: 53,
        totalReports: 6100,
        pendingReview: 3,
        reviewedToday: 50,
        passRate: 95.0,
        avgReviewMinutes: 14.5,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-03',
    name: '中共峡江县委宣传部',
    code: 'XJ-XC-004',
    level: 1,
    type: 'head',
    industry: '宣传报道',
    region: '江西/吉安/峡江县',
    leader: '张锐',
    leaderPhone: '158****2653',
    statusType: '正式',
    totalPersonnel: 145,
    activePersonnel: 118,
    qrLimit: 160,
    qrUsed: 145,
    todayReports: 68,
    totalReports: 7890,
    pendingReview: 4,
    reviewedToday: 64,
    passRate: 97.0,
    avgReviewMinutes: 10.2,
    healthStatus: 'healthy',
    children: [
      {
        id: 'XJ-01',
        name: '峡江县融媒体中心播报组',
        code: 'XJ-RM-01',
        level: 2,
        type: 'branch',
        industry: '融媒体播报',
        region: '吉安/峡江县',
        leader: '肖玉林',
        leaderPhone: '139****1154',
        statusType: '正式',
        totalPersonnel: 85,
        activePersonnel: 72,
        qrLimit: 95,
        qrUsed: 85,
        todayReports: 42,
        totalReports: 4980,
        pendingReview: 2,
        reviewedToday: 40,
        passRate: 97.5,
        avgReviewMinutes: 9.5,
        healthStatus: 'healthy',
      },
      {
        id: 'XJ-02',
        name: '水边镇基层网信通讯联络站',
        code: 'XJ-SB-02',
        level: 2,
        type: 'grid_station',
        industry: '乡镇网格',
        region: '峡江/水边镇',
        leader: '廖建国',
        leaderPhone: '136****7732',
        statusType: '正式',
        totalPersonnel: 60,
        activePersonnel: 46,
        qrLimit: 65,
        qrUsed: 60,
        todayReports: 26,
        totalReports: 2910,
        pendingReview: 2,
        reviewedToday: 24,
        passRate: 96.2,
        avgReviewMinutes: 11.0,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-02',
    name: '河南城建学院融媒中心',
    code: 'HN-CJ-005',
    level: 1,
    type: 'head',
    industry: '高校职校',
    region: '河南/平顶山市',
    leader: '郭凯',
    leaderPhone: '166****9070',
    statusType: '试用',
    totalPersonnel: 180,
    activePersonnel: 142,
    qrLimit: 200,
    qrUsed: 180,
    todayReports: 88,
    totalReports: 9450,
    pendingReview: 5,
    reviewedToday: 83,
    passRate: 98.1,
    avgReviewMinutes: 8.8,
    healthStatus: 'healthy',
    children: [
      {
        id: 'HN-CJ-01',
        name: '党委宣传部大学生网络记者团',
        code: 'HN-CJ-JZ',
        level: 2,
        type: 'branch',
        industry: '高校融媒',
        region: '平顶山/新城区',
        leader: '宋雨晴',
        leaderPhone: '185****1209',
        statusType: '试用',
        totalPersonnel: 110,
        activePersonnel: 90,
        qrLimit: 120,
        qrUsed: 110,
        todayReports: 56,
        totalReports: 6120,
        pendingReview: 3,
        reviewedToday: 53,
        passRate: 98.5,
        avgReviewMinutes: 7.9,
        healthStatus: 'healthy',
      },
      {
        id: 'HN-CJ-02',
        name: '计算机学院网络文明观察站',
        code: 'HN-CJ-CS',
        level: 2,
        type: 'department',
        industry: '学院工作站',
        region: '平顶山/校本部',
        leader: '张志诚',
        leaderPhone: '186****9988',
        statusType: '试用',
        totalPersonnel: 70,
        activePersonnel: 52,
        qrLimit: 80,
        qrUsed: 70,
        todayReports: 32,
        totalReports: 3330,
        pendingReview: 2,
        reviewedToday: 30,
        passRate: 97.4,
        avgReviewMinutes: 9.6,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-06',
    name: '中共洛阳市委网络安全和信息化委员会办公室',
    code: 'LY-WX-006',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '河南/洛阳市',
    leader: '李龙锐',
    leaderPhone: '176****3418',
    statusType: '正式',
    totalPersonnel: 380,
    activePersonnel: 310,
    qrLimit: 420,
    qrUsed: 380,
    todayReports: 196,
    totalReports: 21300,
    pendingReview: 11,
    reviewedToday: 185,
    passRate: 95.1,
    avgReviewMinutes: 13.8,
    healthStatus: 'healthy',
    children: [
      {
        id: 'LY-01',
        name: '涧西区融媒体中心网络部',
        code: 'LY-JX-01',
        level: 2,
        type: 'branch',
        industry: '融媒体中心',
        region: '洛阳/涧西区',
        leader: '杜文斌',
        leaderPhone: '138****7741',
        statusType: '正式',
        totalPersonnel: 140,
        activePersonnel: 115,
        qrLimit: 155,
        qrUsed: 140,
        todayReports: 74,
        totalReports: 8100,
        pendingReview: 4,
        reviewedToday: 70,
        passRate: 95.8,
        avgReviewMinutes: 12.5,
        healthStatus: 'healthy',
      },
      {
        id: 'LY-02',
        name: '洛龙区网络指挥与民情速报站',
        code: 'LY-LL-02',
        level: 2,
        type: 'branch',
        industry: '网格速报',
        region: '洛阳/洛龙区',
        leader: '马小东',
        leaderPhone: '136****5590',
        statusType: '正式',
        totalPersonnel: 150,
        activePersonnel: 125,
        qrLimit: 165,
        qrUsed: 150,
        todayReports: 80,
        totalReports: 8750,
        pendingReview: 5,
        reviewedToday: 75,
        passRate: 94.6,
        avgReviewMinutes: 14.8,
        healthStatus: 'busy',
      },
      {
        id: 'LY-03',
        name: '西工区网络巡查应急工作组',
        code: 'LY-XG-03',
        level: 2,
        type: 'department',
        industry: '应急巡查',
        region: '洛阳/西工区',
        leader: '范雪梅',
        leaderPhone: '139****3321',
        statusType: '正式',
        totalPersonnel: 90,
        activePersonnel: 70,
        qrLimit: 100,
        qrUsed: 90,
        todayReports: 42,
        totalReports: 4450,
        pendingReview: 2,
        reviewedToday: 40,
        passRate: 96.0,
        avgReviewMinutes: 11.2,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-10',
    name: '漯河市消防救援支队融媒体中心',
    code: 'LH-XF-007',
    level: 1,
    type: 'head',
    industry: '应急消防',
    region: '河南/漯河市',
    leader: '李学坚',
    leaderPhone: '186****8245',
    statusType: '正式',
    totalPersonnel: 160,
    activePersonnel: 135,
    qrLimit: 180,
    qrUsed: 160,
    todayReports: 76,
    totalReports: 8210,
    pendingReview: 3,
    reviewedToday: 73,
    passRate: 97.2,
    avgReviewMinutes: 9.8,
    healthStatus: 'healthy',
    children: [
      {
        id: 'LH-01',
        name: '源汇区消防大队现场速报排',
        code: 'LH-YH-01',
        level: 2,
        type: 'branch',
        industry: '消防速报',
        region: '漯河/源汇区',
        leader: '王强',
        leaderPhone: '138****0091',
        statusType: '正式',
        totalPersonnel: 90,
        activePersonnel: 78,
        qrLimit: 100,
        qrUsed: 90,
        todayReports: 44,
        totalReports: 4720,
        pendingReview: 2,
        reviewedToday: 42,
        passRate: 97.5,
        avgReviewMinutes: 9.2,
        healthStatus: 'healthy',
      },
      {
        id: 'LH-02',
        name: '郾城区应急宣传与防火观察站',
        code: 'LH-YC-02',
        level: 2,
        type: 'branch',
        industry: '消防网格',
        region: '漯河/郾城区',
        leader: '刘海鹏',
        leaderPhone: '135****4489',
        statusType: '正式',
        totalPersonnel: 70,
        activePersonnel: 57,
        qrLimit: 80,
        qrUsed: 70,
        todayReports: 32,
        totalReports: 3490,
        pendingReview: 1,
        reviewedToday: 31,
        passRate: 96.8,
        avgReviewMinutes: 10.5,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-13',
    name: '武汉市网络安全应急指挥中心',
    code: 'WH-WX-008',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '湖北/武汉市',
    leader: '周小芳',
    leaderPhone: '135****6677',
    statusType: '正式',
    totalPersonnel: 520,
    activePersonnel: 430,
    qrLimit: 600,
    qrUsed: 520,
    todayReports: 285,
    totalReports: 32100,
    pendingReview: 16,
    reviewedToday: 269,
    passRate: 95.6,
    avgReviewMinutes: 12.0,
    healthStatus: 'healthy',
    children: [
      {
        id: 'WH-01',
        name: '江汉区融媒体网络采编室',
        code: 'WH-JH-01',
        level: 2,
        type: 'branch',
        industry: '融媒体中心',
        region: '武汉/江汉区',
        leader: '胡振华',
        leaderPhone: '139****7712',
        statusType: '正式',
        totalPersonnel: 180,
        activePersonnel: 150,
        qrLimit: 210,
        qrUsed: 180,
        todayReports: 98,
        totalReports: 11200,
        pendingReview: 6,
        reviewedToday: 92,
        passRate: 95.8,
        avgReviewMinutes: 11.4,
        healthStatus: 'healthy',
      },
      {
        id: 'WH-02',
        name: '武昌区舆情速报与网格监测站',
        code: 'WH-WC-02',
        level: 2,
        type: 'branch',
        industry: '网格舆情',
        region: '武汉/武昌区',
        leader: '唐婉清',
        leaderPhone: '137****4490',
        statusType: '正式',
        totalPersonnel: 190,
        activePersonnel: 158,
        qrLimit: 220,
        qrUsed: 190,
        todayReports: 108,
        totalReports: 12400,
        pendingReview: 7,
        reviewedToday: 101,
        passRate: 95.2,
        avgReviewMinutes: 12.8,
        healthStatus: 'busy',
      },
      {
        id: 'WH-03',
        name: '东湖高新区网络创新实验联络站',
        code: 'WH-DH-03',
        level: 2,
        type: 'department',
        industry: '高新实验',
        region: '武汉/东湖高新',
        leader: '魏子涵',
        leaderPhone: '150****8823',
        statusType: '正式',
        totalPersonnel: 150,
        activePersonnel: 122,
        qrLimit: 170,
        qrUsed: 150,
        todayReports: 79,
        totalReports: 8500,
        pendingReview: 3,
        reviewedToday: 76,
        passRate: 96.2,
        avgReviewMinutes: 10.6,
        healthStatus: 'healthy',
      },
    ],
  },
  {
    id: 'INST-07',
    name: '焦作市委宣传部融媒体中心',
    code: 'JZ-XC-009',
    level: 1,
    type: 'head',
    industry: '宣传报道',
    region: '河南/焦作市',
    leader: '李鹏飞',
    leaderPhone: '187****8601',
    statusType: '试用',
    totalPersonnel: 135,
    activePersonnel: 108,
    qrLimit: 150,
    qrUsed: 135,
    todayReports: 62,
    totalReports: 6780,
    pendingReview: 3,
    reviewedToday: 59,
    passRate: 96.8,
    avgReviewMinutes: 10.5,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-08',
    name: '平顶山市高新区教育体育局速报网络',
    code: 'PD-JY-010',
    level: 1,
    type: 'head',
    industry: '教育系统',
    region: '河南/平顶山市',
    leader: '王维',
    leaderPhone: '139****1122',
    statusType: '正式',
    totalPersonnel: 120,
    activePersonnel: 95,
    qrLimit: 130,
    qrUsed: 120,
    todayReports: 54,
    totalReports: 5900,
    pendingReview: 2,
    reviewedToday: 52,
    passRate: 98.0,
    avgReviewMinutes: 8.5,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-09',
    name: '开封市委网信办综合应急处',
    code: 'KF-WX-011',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '河南/开封市',
    leader: '张锐',
    leaderPhone: '158****2653',
    statusType: '正式',
    totalPersonnel: 210,
    activePersonnel: 175,
    qrLimit: 230,
    qrUsed: 210,
    todayReports: 95,
    totalReports: 11050,
    pendingReview: 5,
    reviewedToday: 90,
    passRate: 96.1,
    avgReviewMinutes: 11.8,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-11',
    name: '商丘市公安局交通警察支队',
    code: 'SQ-GA-012',
    level: 1,
    type: 'head',
    industry: '公安交警',
    region: '河南/商丘市',
    leader: '赵四海',
    leaderPhone: '138****9988',
    statusType: '正式',
    totalPersonnel: 280,
    activePersonnel: 230,
    qrLimit: 300,
    qrUsed: 280,
    todayReports: 135,
    totalReports: 15600,
    pendingReview: 7,
    reviewedToday: 128,
    passRate: 97.4,
    avgReviewMinutes: 9.2,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-12',
    name: '郑州市文化广电和旅游局',
    code: 'ZZ-WG-013',
    level: 1,
    type: 'head',
    industry: '文旅政务',
    region: '河南/郑州市',
    leader: '陈敏',
    leaderPhone: '159****3344',
    statusType: '正式',
    totalPersonnel: 195,
    activePersonnel: 160,
    qrLimit: 220,
    qrUsed: 195,
    todayReports: 86,
    totalReports: 9800,
    pendingReview: 4,
    reviewedToday: 82,
    passRate: 96.5,
    avgReviewMinutes: 10.4,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-14',
    name: '许昌市应急管理局',
    code: 'XC-YJ-014',
    level: 1,
    type: 'head',
    industry: '应急管理',
    region: '河南/许昌市',
    leader: '孙立新',
    leaderPhone: '136****5566',
    statusType: '正式',
    totalPersonnel: 175,
    activePersonnel: 145,
    qrLimit: 200,
    qrUsed: 175,
    todayReports: 78,
    totalReports: 8900,
    pendingReview: 3,
    reviewedToday: 75,
    passRate: 97.0,
    avgReviewMinutes: 10.0,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-15',
    name: '新乡医学院党委宣传部',
    code: 'XX-YX-015',
    level: 1,
    type: 'head',
    industry: '高校职校',
    region: '河南/新乡市',
    leader: '冯淑敏',
    leaderPhone: '185****7788',
    statusType: '试用',
    totalPersonnel: 140,
    activePersonnel: 115,
    qrLimit: 160,
    qrUsed: 140,
    todayReports: 60,
    totalReports: 6800,
    pendingReview: 3,
    reviewedToday: 57,
    passRate: 98.2,
    avgReviewMinutes: 8.2,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-16',
    name: '安阳市融媒体中心',
    code: 'AY-RM-016',
    level: 1,
    type: 'head',
    industry: '融媒体中心',
    region: '河南/安阳市',
    leader: '韩建华',
    leaderPhone: '137****1199',
    statusType: '正式',
    totalPersonnel: 220,
    activePersonnel: 180,
    qrLimit: 250,
    qrUsed: 220,
    todayReports: 105,
    totalReports: 12300,
    pendingReview: 6,
    reviewedToday: 99,
    passRate: 95.8,
    avgReviewMinutes: 11.2,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-17',
    name: '南阳市委网信办直属工作站',
    code: 'NY-WX-017',
    level: 1,
    type: 'head',
    industry: '网信部门',
    region: '河南/南阳市',
    leader: '杨光耀',
    leaderPhone: '139****4455',
    statusType: '正式',
    totalPersonnel: 260,
    activePersonnel: 215,
    qrLimit: 290,
    qrUsed: 260,
    todayReports: 125,
    totalReports: 14600,
    pendingReview: 7,
    reviewedToday: 118,
    passRate: 96.0,
    avgReviewMinutes: 12.1,
    healthStatus: 'healthy',
  },
  {
    id: 'INST-18',
    name: '信阳市生态环境局宣传处',
    code: 'XY-ST-018',
    level: 1,
    type: 'head',
    industry: '生态环保',
    region: '河南/信阳市',
    leader: '董海龙',
    leaderPhone: '158****6677',
    statusType: '正式',
    totalPersonnel: 130,
    activePersonnel: 105,
    qrLimit: 150,
    qrUsed: 130,
    todayReports: 58,
    totalReports: 6400,
    pendingReview: 2,
    reviewedToday: 56,
    passRate: 97.5,
    avgReviewMinutes: 9.6,
    healthStatus: 'healthy',
  },
];

export const mockPersonnelList: PersonnelItem[] = [
  {
    id: 'P001',
    name: '王俊杰',
    avatarColor: 'bg-indigo-600',
    role: '首席采编员',
    institutionId: 'INST-05',
    institutionName: '随州市网信中心',
    subBranchName: '随县网络安全速报与应急处突分队',
    phone: '138****5621',
    todayReports: 12,
    totalReports: 1420,
    todayReviewed: 0,
    passRate: 99.1,
    avgResponseMins: 6.5,
    status: 'online',
    lastActive: '1分钟前',
  },
  {
    id: 'P002',
    name: '刘晓丽',
    avatarColor: 'bg-emerald-600',
    role: '初审专员',
    institutionId: 'INST-05',
    institutionName: '随州市网信中心',
    subBranchName: '曾都区融媒体中心网络采编部',
    phone: '139****8832',
    todayReports: 0,
    totalReports: 15,
    todayReviewed: 44,
    passRate: 97.5,
    avgResponseMins: 8.2,
    status: 'busy',
    lastActive: '刚刚',
  },
  {
    id: 'P003',
    name: '张建国',
    avatarColor: 'bg-blue-600',
    role: '终审主管',
    institutionId: 'INST-05',
    institutionName: '随州市网信中心',
    subBranchName: '广水市网信办融媒指挥分中心',
    phone: '137****9012',
    todayReports: 0,
    totalReports: 28,
    todayReviewed: 52,
    passRate: 96.0,
    avgResponseMins: 11.0,
    status: 'online',
    lastActive: '5分钟前',
  },
  {
    id: 'P004',
    name: '陈思齐',
    avatarColor: 'bg-purple-600',
    role: '网格速报员',
    institutionId: 'INST-05',
    institutionName: '随州市网信中心',
    subBranchName: '南郊街道网格化速报工作站',
    phone: '135****4423',
    todayReports: 9,
    totalReports: 890,
    todayReviewed: 0,
    passRate: 98.4,
    avgResponseMins: 5.8,
    status: 'online',
    lastActive: '3分钟前',
  },
  {
    id: 'P005',
    name: '李鹏飞',
    avatarColor: 'bg-amber-600',
    role: '终审主管',
    institutionId: 'INST-01',
    institutionName: '国网商丘供电公司',
    subBranchName: '梁园区电力安全与融媒通讯部',
    phone: '187****8601',
    todayReports: 0,
    totalReports: 42,
    todayReviewed: 62,
    passRate: 96.2,
    avgResponseMins: 12.4,
    status: 'online',
    lastActive: '10分钟前',
  },
  {
    id: 'P006',
    name: '何伟强',
    avatarColor: 'bg-rose-600',
    role: '初审专员',
    institutionId: 'INST-04',
    institutionName: '佛山市委网信办',
    subBranchName: '禅城区融媒体网信直报中心',
    phone: '137****3310',
    todayReports: 0,
    totalReports: 10,
    todayReviewed: 73,
    passRate: 94.5,
    avgResponseMins: 14.2,
    status: 'busy',
    lastActive: '刚刚',
  },
  {
    id: 'P007',
    name: '宋雨晴',
    avatarColor: 'bg-pink-600',
    role: '首席采编员',
    institutionId: 'INST-02',
    institutionName: '河南城建学院',
    subBranchName: '党委宣传部大学生网络记者团',
    phone: '185****1209',
    todayReports: 15,
    totalReports: 980,
    todayReviewed: 0,
    passRate: 99.5,
    avgResponseMins: 4.5,
    status: 'online',
    lastActive: '刚刚',
  },
  {
    id: 'P008',
    name: '魏子涵',
    avatarColor: 'bg-cyan-600',
    role: '网安特派员',
    institutionId: 'INST-13',
    institutionName: '武汉市网络安全应急指挥中心',
    subBranchName: '东湖高新区网络创新实验联络站',
    phone: '150****8823',
    todayReports: 8,
    totalReports: 760,
    todayReviewed: 25,
    passRate: 97.0,
    avgResponseMins: 7.8,
    status: 'online',
    lastActive: '2分钟前',
  },
];

export const mockReportReviewEvents: ReportReviewEvent[] = [
  {
    id: 'EVT-20260827-0941',
    title: '随县厉山镇神农文化遗址周边汛期防汛与游客出行指引速报',
    category: '政务发布',
    urgency: '高',
    institutionName: '随州市网信中心',
    subBranchName: '随县网络安全速报与应急处突分队',
    reporterName: '王俊杰',
    reporterRole: '首席采编员',
    reviewerName: '张建国 (终审主管)',
    status: 'approved',
    reportTime: '2026-08-27 10:14:22',
    reviewTime: '2026-08-27 10:22:05',
    durationMins: 7.7,
    score: 98,
  },
  {
    id: 'EVT-20260827-0940',
    title: '商丘市梁园区某10kV变电站线路带电抢修安全保障快报',
    category: '舆情快报',
    urgency: '中',
    institutionName: '国网商丘供电公司',
    subBranchName: '梁园区电力安全与融媒通讯部',
    reporterName: '程明轩',
    reporterRole: '首席采编员',
    reviewerName: '李鹏飞 (初审专员)',
    status: 'approved',
    reportTime: '2026-08-27 10:08:15',
    reviewTime: '2026-08-27 10:19:40',
    durationMins: 11.4,
    score: 95,
  },
  {
    id: 'EVT-20260827-0939',
    title: '佛山市南海区某工业园消防疏散演练涉网络不实谣言澄清通报',
    category: '不良举报',
    urgency: '高',
    institutionName: '佛山市委网信办',
    subBranchName: '南海区网络安全与舆情应急中心',
    reporterName: '梁志锋',
    reporterRole: '网格速报员',
    reviewerName: '何伟强 (初审专员)',
    status: 'pending_final',
    reportTime: '2026-08-27 10:02:50',
    durationMins: 18.2,
  },
  {
    id: 'EVT-20260827-0938',
    title: '河南城建学院2026迎新季校园生活服务专栏与反诈提示',
    category: '政务发布',
    urgency: '普通',
    institutionName: '河南城建学院',
    subBranchName: '党委宣传部大学生网络记者团',
    reporterName: '宋雨晴',
    reporterRole: '首席采编员',
    reviewerName: '郭凯 (终审主管)',
    status: 'approved',
    reportTime: '2026-08-27 09:55:10',
    reviewTime: '2026-08-27 10:01:20',
    durationMins: 6.1,
    score: 99,
  },
  {
    id: 'EVT-20260827-0937',
    title: '曾都区南郊街道某生鲜市场价格稳定情况网格化日巡查',
    category: '网格巡查',
    urgency: '普通',
    institutionName: '随州市网信中心',
    subBranchName: '南郊街道网格化速报工作站',
    reporterName: '陈思齐',
    reporterRole: '网格速报员',
    status: 'pending_first',
    reportTime: '2026-08-27 09:50:33',
  },
  {
    id: 'EVT-20260827-0936',
    title: '某自媒体短视频涉夸大洛阳某景区排队冲突不实剪辑处置',
    category: '应急速报',
    urgency: '高',
    institutionName: '洛阳市委网信办',
    subBranchName: '洛龙区网络指挥与民情速报站',
    reporterName: '马小东',
    reporterRole: '网格速报员',
    reviewerName: '杜文斌 (初审专员)',
    status: 'approved',
    reportTime: '2026-08-27 09:35:12',
    reviewTime: '2026-08-27 09:48:00',
    durationMins: 12.8,
    score: 96,
  },
  {
    id: 'EVT-20260827-0935',
    title: '武汉东湖高新区某科技园网络宽带临时割接施工提醒公告',
    category: '政务发布',
    urgency: '普通',
    institutionName: '武汉市网络安全应急指挥中心',
    subBranchName: '东湖高新区网络创新实验联络站',
    reporterName: '魏子涵',
    reporterRole: '网安特派员',
    reviewerName: '胡振华 (初审专员)',
    status: 'rejected',
    reportTime: '2026-08-27 09:20:10',
    reviewTime: '2026-08-27 09:29:40',
    durationMins: 9.5,
    rejectReason: '未附具电信运营商官方施工批复文件编号，请补充后重报',
  },
];
