import { Institution, ExpiringInstitution, AuditLog } from './types';

export const initialExpiringInstitutions: ExpiringInstitution[] = [
  {
    id: 1,
    name: '国网河南省电力公司商丘供电公司',
    status: '正式',
    region: '河南/商丘',
    category: '二类',
    industry: '电力',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    startDate: '2025-08-24',
    endDate: '2026-09-08',
    expireTime: '2026-09-08 00:00:00',
    daysRemaining: 15,
    countdownText: '15天',
    isExpired: false,
  },
  {
    id: 2,
    name: '河南城建学院',
    status: '试用',
    region: '河南/平顶山',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    startDate: '2026-08-24',
    endDate: '2026-09-23',
    expireTime: '2026-09-23 00:00:00',
    daysRemaining: 15,
    countdownText: '15天',
    isExpired: false,
  },
  {
    id: 3,
    name: '中共峡江县委宣传部',
    status: '正式',
    region: '江西/吉安市/峡江县',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    startDate: '2025-09-01',
    endDate: '2026-08-26',
    expireTime: '2026-08-26 18:00:00',
    daysRemaining: 0,
    countdownText: '08时47分',
    isExpired: false,
  },
  {
    id: 4,
    name: '中共佛山市委网络安全和信息化委员会办公室',
    status: '试用',
    region: '广东/佛山市',
    category: '一类',
    industry: '网信部门',
    salesName: '李学坚',
    salesPhone: '186****8245',
    startDate: '2026-08-21',
    endDate: '2026-08-25',
    expireTime: '2026-08-25 00:00:00',
    daysRemaining: 1,
    countdownText: '已到期',
    isExpired: true,
  },
  {
    id: 5,
    name: '随州市网信中心（随州市网络安全应急指挥中心）',
    status: '正式',
    region: '湖北/随州市',
    category: '一类',
    industry: '网信部门',
    salesName: '廖伟',
    salesPhone: '189****4954',
    startDate: '2025-08-20',
    endDate: '2026-08-25',
    expireTime: '2026-08-25 00:00:00',
    daysRemaining: 1,
    countdownText: '已到期',
    isExpired: true,
  },
  {
    id: 6,
    name: '中共洛阳市委网络安全和信息化委员会办公室',
    status: '正式',
    region: '河南/洛阳',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    startDate: '2025-09-18',
    endDate: '2026-09-18',
    expireTime: '2026-09-18 00:00:00',
    daysRemaining: 14,
    countdownText: '14天',
    isExpired: false,
  },
  {
    id: 7,
    name: '焦作市委宣传部',
    status: '试用',
    region: '河南/焦作',
    category: '二类',
    industry: '宣传部',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    startDate: '2026-08-01',
    endDate: '2026-10-10',
    expireTime: '2026-10-10 00:00:00',
    daysRemaining: 45,
    countdownText: '45天',
    isExpired: false,
  },
  {
    id: 8,
    name: '平顶山市高新区教育体育局',
    status: '正式',
    region: '河南/平顶山',
    category: '二类',
    industry: '教育',
    salesName: '王维',
    salesPhone: '139****1122',
    startDate: '2025-08-24',
    endDate: '2026-09-09',
    expireTime: '2026-09-09 00:00:00',
    daysRemaining: 14,
    countdownText: '14天',
    isExpired: false,
  },
  {
    id: 9,
    name: '开封市委网信办',
    status: '正式',
    region: '河南/开封',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    startDate: '2025-09-09',
    endDate: '2026-09-09',
    expireTime: '2026-09-09 00:00:00',
    daysRemaining: 14,
    countdownText: '14天',
    isExpired: false,
  },
  {
    id: 10,
    name: '漯河市消防救援支队',
    status: '试用',
    region: '河南/漯河',
    category: '二类',
    industry: '消防',
    salesName: '李学坚',
    salesPhone: '186****8245',
    startDate: '2026-08-25',
    endDate: '2026-08-25',
    expireTime: '2026-08-25 00:00:00',
    daysRemaining: 1,
    countdownText: '已到期',
    isExpired: true,
  },
  {
    id: 11,
    name: '驻马店市委网信办',
    status: '正式',
    region: '河南/驻马店',
    category: '一类',
    industry: '网信部门',
    salesName: '郭凯',
    salesPhone: '166****9070',
    startDate: '2025-09-25',
    endDate: '2026-09-25',
    expireTime: '2026-09-25 00:00:00',
    daysRemaining: 30,
    countdownText: '30天',
    isExpired: false,
  },
  {
    id: 12,
    name: '杭州市临安区融媒体中心',
    status: '正式',
    region: '浙江/杭州/临安',
    category: '一类',
    industry: '融媒体中心',
    salesName: '李学坚',
    salesPhone: '186****8245',
    startDate: '2025-09-25',
    endDate: '2026-09-25',
    expireTime: '2026-09-25 00:00:00',
    daysRemaining: 30,
    countdownText: '30天',
    isExpired: false,
  },
  {
    id: 13,
    name: '武汉市网络安全应急指挥中心',
    status: '正式',
    region: '湖北/武汉',
    category: '一类',
    industry: '网信部门',
    salesName: '周小芳',
    salesPhone: '135****6677',
    startDate: '2025-09-25',
    endDate: '2026-09-25',
    expireTime: '2026-09-25 00:00:00',
    daysRemaining: 30,
    countdownText: '30天',
    isExpired: false,
  },
  {
    id: 14,
    name: '北京开元融媒体技术有限公司',
    status: '正式',
    region: '北京/海淀区',
    category: '一类',
    industry: '媒体发布',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    startDate: '2025-10-01',
    endDate: '2026-09-20',
    expireTime: '2026-09-20 00:00:00',
    daysRemaining: 25,
    countdownText: '25天',
    isExpired: false,
  },
  {
    id: 15,
    name: '广州日报报业集团',
    status: '正式',
    region: '广东/广州市',
    category: '一类',
    industry: '媒体发布',
    salesName: '刘强',
    salesPhone: '139****8888',
    startDate: '2025-09-15',
    endDate: '2026-09-15',
    expireTime: '2026-09-15 00:00:00',
    daysRemaining: 20,
    countdownText: '20天',
    isExpired: false,
  },
  {
    id: 16,
    name: '四川省公安厅网络安全保卫总队',
    status: '试用',
    region: '四川/成都',
    category: '一类',
    industry: '网安部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    startDate: '2026-08-10',
    endDate: '2026-09-10',
    expireTime: '2026-09-10 00:00:00',
    daysRemaining: 15,
    countdownText: '15天',
    isExpired: false,
  },
];

export const initialInstitutions: Institution[] = [
  // ==================== 第 1 页 (1 - 30) ====================
  {
    id: 1,
    name: '国网河南省电力公司商丘供电公司',
    status: '正式',
    location: '河南/商丘',
    category: '二类',
    industry: '电力',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2025-08-24',
    endDate: '2026-09-08',
    daysRemaining: 15,
    unitName: '商丘供电单元',
  },
  {
    id: 2,
    name: '河南城建学院',
    status: '试用',
    location: '河南/平顶山',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2026-08-24',
    endDate: '2026-09-23',
    daysRemaining: 15,
    unitName: '城建大楼单元',
  },
  {
    id: 3,
    name: '中共峡江县委宣传部',
    status: '正式',
    location: '江西/吉安市/峡江县',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: false,
    startDate: '2025-09-01',
    endDate: '2026-08-26',
    daysRemaining: 0,
    unitName: '峡江网信单元',
  },
  {
    id: 4,
    name: '中共佛山市委网络安全和信息化委员会办公室',
    status: '试用',
    location: '广东/佛山市',
    category: '一类',
    industry: '网信部门',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-10',
    endDate: '2026-09-10',
    daysRemaining: 16,
    unitName: '佛山网信中心',
  },
  {
    id: 5,
    name: '随州市网信中心（随州市网络安全应急指挥中心）',
    status: '正式',
    location: '湖北/随州市',
    category: '一类',
    industry: '网信部门',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: false,
    startDate: '2025-08-20',
    endDate: '2026-08-25',
    daysRemaining: 0,
    unitName: '随州网信中心单元',
  },
  {
    id: 6,
    name: '中共洛阳市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '河南/洛阳',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    enabled: true,
    startDate: '2025-09-18',
    endDate: '2026-09-18',
    daysRemaining: 23,
    unitName: '洛阳网信办',
  },
  {
    id: 7,
    name: '四川省公安厅网络安全保卫总队',
    status: '试用',
    location: '四川/成都',
    category: '一类',
    industry: '网安部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-06',
    endDate: '2026-09-06',
    daysRemaining: 12,
    unitName: '四川公安网安组',
  },
  {
    id: 8,
    name: '北京开元融媒体技术有限公司',
    status: '正式',
    location: '北京/海淀区',
    category: '一类',
    industry: '媒体发布',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    daysRemaining: 127,
    unitName: '开元融媒单元',
  },
  {
    id: 9,
    name: '焦作市委宣传部',
    status: '试用',
    location: '河南/焦作',
    category: '一类',
    industry: '网信部门',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2026-08-15',
    endDate: '2026-09-15',
    daysRemaining: 21,
    unitName: '焦作宣传单元',
  },
  {
    id: 10,
    name: '广州日报报业集团',
    status: '正式',
    location: '广东/广州市',
    category: '一类',
    industry: '媒体发布',
    salesName: '刘强',
    salesPhone: '139****8888',
    enabled: true,
    startDate: '2025-05-15',
    endDate: '2027-05-14',
    daysRemaining: 261,
    unitName: '广报传媒中心',
  },
  {
    id: 11,
    name: '平顶山市高新区教育体育局',
    status: '正式',
    location: '河南/平顶山',
    category: '二类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2025-09-01',
    endDate: '2026-09-01',
    daysRemaining: 6,
    unitName: '平顶山教体单元',
  },
  {
    id: 12,
    name: '开封市委网信办',
    status: '正式',
    location: '河南/开封',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: true,
    startDate: '2025-09-09',
    endDate: '2026-09-09',
    daysRemaining: 14,
    unitName: '开封网信单元',
  },
  {
    id: 13,
    name: '浙江大学计算机创新技术研究院',
    status: '试用',
    location: '浙江/杭州市',
    category: '二类',
    industry: '职校高校',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: false,
    startDate: '2026-08-01',
    endDate: '2026-08-25',
    daysRemaining: 0,
    unitName: '浙大创研单元',
  },
  {
    id: 14,
    name: '驻马店市委网信办',
    status: '正式',
    location: '河南/驻马店',
    category: '一类',
    industry: '网信部门',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2025-09-25',
    endDate: '2026-09-25',
    daysRemaining: 30,
    unitName: '驻马店网信办',
  },
  {
    id: 15,
    name: '上海张江高科技园区文化中心',
    status: '正式',
    location: '上海/浦东新区',
    category: '二类',
    industry: '职校高校',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2025-09-01',
    endDate: '2026-08-31',
    daysRemaining: 5,
    unitName: '张江文化单元',
  },
  {
    id: 16,
    name: '江苏省电力科学研究院',
    status: '试用',
    location: '江苏/南京市',
    category: '二类',
    industry: '电力',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2026-08-10',
    endDate: '2026-09-10',
    daysRemaining: 15,
    unitName: '苏电科研所',
  },
  {
    id: 17,
    name: '武汉市广播电视台',
    status: '正式',
    location: '湖北/武汉市',
    category: '一类',
    industry: '广电广播',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: false,
    startDate: '2024-06-01',
    endDate: '2025-06-01',
    daysRemaining: 0,
    unitName: '武汉广电单元',
  },
  {
    id: 18,
    name: '深圳市南山区融媒体中心',
    status: '试用',
    location: '广东/深圳市',
    category: '一类',
    industry: '媒体发布',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-15',
    endDate: '2026-09-30',
    daysRemaining: 35,
    unitName: '南山融媒中心',
  },
  {
    id: 19,
    name: '山东省交通运输厅调度指挥中心',
    status: '正式',
    location: '山东/济南市',
    category: '一类',
    industry: '交通运输',
    salesName: '孙浩',
    salesPhone: '136****9912',
    enabled: true,
    startDate: '2025-11-01',
    endDate: '2026-11-01',
    daysRemaining: 67,
    unitName: '鲁交调度单元',
  },
  {
    id: 20,
    name: '成都市第一人民医院信息化办公室',
    status: '试用',
    location: '四川/成都市',
    category: '二类',
    industry: '医疗健康',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-20',
    endDate: '2026-09-20',
    daysRemaining: 25,
    unitName: '成医信息单元',
  },
  {
    id: 21,
    name: '中共成都市青羊区委组织部',
    status: '试用',
    location: '四川/成都市',
    category: '一类',
    industry: '政务服务',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    daysRemaining: 5,
    unitName: '青羊组织单元',
  },
  {
    id: 22,
    name: '国网湖南省电力有限公司长沙供电分公司',
    status: '正式',
    location: '湖南/长沙市',
    category: '二类',
    industry: '电力',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: false,
    startDate: '2025-07-01',
    endDate: '2026-07-01',
    daysRemaining: 0,
    unitName: '长沙供电单元',
  },
  {
    id: 23,
    name: '厦门市金融数据监测中心',
    status: '试用',
    location: '福建/厦门市',
    category: '一类',
    industry: '金融证券',
    salesName: '钱琳',
    salesPhone: '185****1290',
    enabled: true,
    startDate: '2026-08-10',
    endDate: '2026-09-25',
    daysRemaining: 30,
    unitName: '厦门金控单元',
  },
  {
    id: 24,
    name: '陕西师范大学网络信息中心',
    status: '试用',
    location: '陕西/西安市',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2026-08-12',
    endDate: '2026-10-12',
    daysRemaining: 47,
    unitName: '陕师大网络部',
  },
  {
    id: 25,
    name: '中共南京市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '江苏/南京市',
    category: '一类',
    industry: '网信部门',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2025-10-15',
    endDate: '2026-10-15',
    daysRemaining: 50,
    unitName: '南京网信单元',
  },
  {
    id: 26,
    name: '合肥高新股份有限公司技术发展部',
    status: '试用',
    location: '安徽/合肥市',
    category: '二类',
    industry: '媒体发布',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: false,
    startDate: '2026-07-20',
    endDate: '2026-08-20',
    daysRemaining: 0,
    unitName: '合肥高新单元',
  },
  {
    id: 27,
    name: '国网山东省电力公司青岛供电公司',
    status: '正式',
    location: '山东/青岛市',
    category: '二类',
    industry: '电力',
    salesName: '孙浩',
    salesPhone: '136****9912',
    enabled: true,
    startDate: '2025-06-01',
    endDate: '2026-09-15',
    daysRemaining: 20,
    unitName: '青岛供电单元',
  },
  {
    id: 28,
    name: '天津市海河传媒中心数字广播部',
    status: '试用',
    location: '天津/河西区',
    category: '一类',
    industry: '广电广播',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2026-08-18',
    endDate: '2026-09-18',
    daysRemaining: 23,
    unitName: '海河传媒单元',
  },
  {
    id: 29,
    name: '中共重庆市渝中区委网络安全和信息化委员会办公室',
    status: '正式',
    location: '重庆/渝中区',
    category: '一类',
    industry: '网信部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2025-04-01',
    endDate: '2027-04-01',
    daysRemaining: 218,
    unitName: '渝中网信单元',
  },
  {
    id: 30,
    name: '江西省水利科学院信息化研究室',
    status: '试用',
    location: '江西/南昌市',
    category: '二类',
    industry: '政务服务',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: true,
    startDate: '2026-08-01',
    endDate: '2026-09-15',
    daysRemaining: 20,
    unitName: '江西水利单元',
  },

  // ==================== 第 2 页 (31 - 60) ====================
  {
    id: 31,
    name: '国网河北省电力有限公司石家庄供电分公司',
    status: '正式',
    location: '河北/石家庄',
    category: '二类',
    industry: '电力',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2025-08-20',
    endDate: '2026-09-10',
    daysRemaining: 15,
    unitName: '石家庄供电组',
  },
  {
    id: 32,
    name: '华中科技大学国家数字建造技术创新中心',
    status: '试用',
    location: '湖北/武汉市',
    category: '三类',
    industry: '职校高校',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: true,
    startDate: '2026-08-22',
    endDate: '2026-09-22',
    daysRemaining: 27,
    unitName: '华科创研单元',
  },
  {
    id: 33,
    name: '中共南昌市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '江西/南昌市',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: false,
    startDate: '2025-08-15',
    endDate: '2026-08-25',
    daysRemaining: 0,
    unitName: '南昌网信单元',
  },
  {
    id: 34,
    name: '珠海市金湾区融媒体中心',
    status: '试用',
    location: '广东/珠海市',
    category: '一类',
    industry: '媒体发布',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-10',
    endDate: '2026-09-20',
    daysRemaining: 25,
    unitName: '金湾融媒中心',
  },
  {
    id: 35,
    name: '中共黄冈市委宣传部舆情中心',
    status: '正式',
    location: '湖北/黄冈市',
    category: '一类',
    industry: '网信部门',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: true,
    startDate: '2025-09-10',
    endDate: '2026-09-10',
    daysRemaining: 15,
    unitName: '黄冈舆情单元',
  },
  {
    id: 36,
    name: '新乡市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '河南/新乡',
    category: '一类',
    industry: '网信部门',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2025-09-20',
    endDate: '2026-09-20',
    daysRemaining: 25,
    unitName: '新乡网信单元',
  },
  {
    id: 37,
    name: '成都市公安局网络安全保卫支队',
    status: '试用',
    location: '四川/成都市',
    category: '一类',
    industry: '网安部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: false,
    startDate: '2026-08-05',
    endDate: '2026-08-25',
    daysRemaining: 0,
    unitName: '成网保卫单元',
  },
  {
    id: 38,
    name: '南方电网数字传媒科技有限公司',
    status: '正式',
    location: '广东/广州市',
    category: '一类',
    industry: '电力',
    salesName: '刘强',
    salesPhone: '139****8888',
    enabled: true,
    startDate: '2025-03-01',
    endDate: '2027-03-01',
    daysRemaining: 187,
    unitName: '南网数媒单元',
  },
  {
    id: 39,
    name: '三门峡市委宣传部',
    status: '试用',
    location: '河南/三门峡',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    enabled: true,
    startDate: '2026-08-16',
    endDate: '2026-09-16',
    daysRemaining: 21,
    unitName: '三门峡宣传部',
  },
  {
    id: 40,
    name: '北京广播电视台新媒体运行中心',
    status: '正式',
    location: '北京/朝阳区',
    category: '一类',
    industry: '广电广播',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2025-05-20',
    endDate: '2026-11-20',
    daysRemaining: 86,
    unitName: '京台新媒中心',
  },
  {
    id: 41,
    name: '许昌职业技术学院信息工程学院',
    status: '正式',
    location: '河南/许昌',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2025-09-05',
    endDate: '2026-09-05',
    daysRemaining: 10,
    unitName: '许昌职院单元',
  },
  {
    id: 42,
    name: '安阳市委网信办综合协调科',
    status: '正式',
    location: '河南/安阳',
    category: '一类',
    industry: '网信部门',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2025-09-12',
    endDate: '2026-09-12',
    daysRemaining: 17,
    unitName: '安阳网信办',
  },
  {
    id: 43,
    name: '复旦大学智能网络与计算中心',
    status: '试用',
    location: '上海/杨浦区',
    category: '三类',
    industry: '职校高校',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2026-08-02',
    endDate: '2026-09-18',
    daysRemaining: 23,
    unitName: '复旦智网单元',
  },
  {
    id: 44,
    name: '信阳市委网信办网络应急中心',
    status: '正式',
    location: '河南/信阳',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    enabled: true,
    startDate: '2025-09-28',
    endDate: '2026-09-28',
    daysRemaining: 33,
    unitName: '信阳应急单元',
  },
  {
    id: 45,
    name: '上海交通大学医学院附属仁济医院',
    status: '正式',
    location: '上海/黄浦区',
    category: '二类',
    industry: '医疗健康',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2025-09-02',
    endDate: '2026-09-02',
    daysRemaining: 7,
    unitName: '仁济医网单元',
  },
  {
    id: 46,
    name: '国网江苏省电力工程咨询有限公司',
    status: '试用',
    location: '江苏/苏州市',
    category: '二类',
    industry: '电力',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2026-08-11',
    endDate: '2026-09-26',
    daysRemaining: 31,
    unitName: '苏电咨询单元',
  },
  {
    id: 47,
    name: '湖南省广播电视局安全监测中心',
    status: '正式',
    location: '湖南/长沙市',
    category: '一类',
    industry: '广电广播',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: false,
    startDate: '2024-08-01',
    endDate: '2025-08-01',
    daysRemaining: 0,
    unitName: '湘广监测单元',
  },
  {
    id: 48,
    name: '东莞市松山湖高新区融媒工作站',
    status: '试用',
    location: '广东/东莞市',
    category: '一类',
    industry: '媒体发布',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-18',
    endDate: '2026-09-18',
    daysRemaining: 23,
    unitName: '松山湖融媒',
  },
  {
    id: 49,
    name: '山东高速智慧交通发展有限公司',
    status: '正式',
    location: '山东/济南市',
    category: '一类',
    industry: '交通运输',
    salesName: '孙浩',
    salesPhone: '136****9912',
    enabled: true,
    startDate: '2025-10-01',
    endDate: '2026-10-01',
    daysRemaining: 36,
    unitName: '山东高速智交',
  },
  {
    id: 50,
    name: '四川大学华西医院网络中心',
    status: '试用',
    location: '四川/成都市',
    category: '二类',
    industry: '医疗健康',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-25',
    endDate: '2026-09-25',
    daysRemaining: 30,
    unitName: '华西信息单元',
  },
  {
    id: 51,
    name: '中共重庆市九龙坡区委组织部',
    status: '试用',
    location: '重庆/九龙坡区',
    category: '一类',
    industry: '政务服务',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-04',
    endDate: '2026-09-04',
    daysRemaining: 9,
    unitName: '九龙坡组织部',
  },
  {
    id: 52,
    name: '国网江西省电力公司九江供电分公司',
    status: '正式',
    location: '江西/九江市',
    category: '二类',
    industry: '电力',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: false,
    startDate: '2025-08-10',
    endDate: '2026-08-24',
    daysRemaining: 0,
    unitName: '九江供电单元',
  },
  {
    id: 53,
    name: '福州市大数据产业运营有限公司',
    status: '试用',
    location: '福建/福州市',
    category: '一类',
    industry: '金融证券',
    salesName: '钱琳',
    salesPhone: '185****1290',
    enabled: true,
    startDate: '2026-08-15',
    endDate: '2026-09-28',
    daysRemaining: 33,
    unitName: '福州数产单元',
  },
  {
    id: 54,
    name: '西安电子科技大学网络空间安全学院',
    status: '试用',
    location: '陕西/西安市',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2026-08-14',
    endDate: '2026-09-30',
    daysRemaining: 35,
    unitName: '西电网安单元',
  },
  {
    id: 55,
    name: '中共无锡市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '江苏/无锡市',
    category: '一类',
    industry: '网信部门',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2025-11-20',
    endDate: '2026-11-20',
    daysRemaining: 86,
    unitName: '无锡网信单元',
  },
  {
    id: 56,
    name: '安徽省广播影视监测中心',
    status: '试用',
    location: '安徽/合肥市',
    category: '二类',
    industry: '广电广播',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: false,
    startDate: '2026-08-01',
    endDate: '2026-09-01',
    daysRemaining: 6,
    unitName: '皖广监测单元',
  },
  {
    id: 57,
    name: '国网浙江省电力有限公司宁波供电公司',
    status: '正式',
    location: '浙江/宁波市',
    category: '二类',
    industry: '电力',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2025-07-15',
    endDate: '2026-09-10',
    daysRemaining: 15,
    unitName: '宁波供电单元',
  },
  {
    id: 58,
    name: '天津港通信信息工程技术有限公司',
    status: '试用',
    location: '天津/滨海新区',
    category: '一类',
    industry: '交通运输',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2026-08-20',
    endDate: '2026-09-20',
    daysRemaining: 25,
    unitName: '津港通信单元',
  },
  {
    id: 59,
    name: '中共成都市武侯区委网络安全和信息化委员会办公室',
    status: '正式',
    location: '四川/成都市',
    category: '一类',
    industry: '网信部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2025-05-01',
    endDate: '2027-05-01',
    daysRemaining: 248,
    unitName: '武侯网信单元',
  },
  {
    id: 60,
    name: '江西财经大学数字化管理研究中心',
    status: '试用',
    location: '江西/南昌市',
    category: '二类',
    industry: '职校高校',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: true,
    startDate: '2026-08-05',
    endDate: '2026-09-19',
    daysRemaining: 24,
    unitName: '江财数管中心',
  },

  // ==================== 第 3 页 (61 - 90) ====================
  {
    id: 61,
    name: '国网陕西省电力有限公司西安供电分公司',
    status: '正式',
    location: '陕西/西安市',
    category: '二类',
    industry: '电力',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2025-08-18',
    endDate: '2026-09-12',
    daysRemaining: 17,
    unitName: '西安供电单元',
  },
  {
    id: 62,
    name: '武汉理工大学智能交通系统研发中心',
    status: '试用',
    location: '湖北/武汉市',
    category: '三类',
    industry: '职校高校',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: true,
    startDate: '2026-08-20',
    endDate: '2026-09-24',
    daysRemaining: 29,
    unitName: '理工智交单元',
  },
  {
    id: 63,
    name: '中共赣州市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '江西/赣州市',
    category: '一类',
    industry: '网信部门',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: false,
    startDate: '2025-08-10',
    endDate: '2026-08-24',
    daysRemaining: 0,
    unitName: '赣州网信单元',
  },
  {
    id: 64,
    name: '中山市融媒体中心新媒体部',
    status: '试用',
    location: '广东/中山市',
    category: '一类',
    industry: '媒体发布',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-12',
    endDate: '2026-09-26',
    daysRemaining: 31,
    unitName: '中山融媒中心',
  },
  {
    id: 65,
    name: '中共襄阳市委宣传部对外宣传科',
    status: '正式',
    location: '湖北/襄阳市',
    category: '一类',
    industry: '网信部门',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: true,
    startDate: '2025-09-15',
    endDate: '2026-09-15',
    daysRemaining: 20,
    unitName: '襄阳外宣单元',
  },
  {
    id: 66,
    name: '濮阳市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '河南/濮阳',
    category: '一类',
    industry: '网信部门',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2025-09-22',
    endDate: '2026-09-22',
    daysRemaining: 27,
    unitName: '濮阳网信单元',
  },
  {
    id: 67,
    name: '绵阳市公安局网络安全保卫支队',
    status: '试用',
    location: '四川/绵阳市',
    category: '一类',
    industry: '网安部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: false,
    startDate: '2026-08-01',
    endDate: '2026-08-25',
    daysRemaining: 0,
    unitName: '绵阳网保支队',
  },
  {
    id: 68,
    name: '中国南方航空股份有限公司数字技术部',
    status: '正式',
    location: '广东/广州市',
    category: '一类',
    industry: '交通运输',
    salesName: '刘强',
    salesPhone: '139****8888',
    enabled: true,
    startDate: '2025-04-10',
    endDate: '2027-04-10',
    daysRemaining: 227,
    unitName: '南航数技单元',
  },
  {
    id: 69,
    name: '鹤壁市委宣传部新闻发布科',
    status: '试用',
    location: '河南/鹤壁',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    enabled: true,
    startDate: '2026-08-19',
    endDate: '2026-09-19',
    daysRemaining: 24,
    unitName: '鹤壁宣传单元',
  },
  {
    id: 70,
    name: '中央广播电视总台亚太总站协同中心',
    status: '正式',
    location: '北京/海淀区',
    category: '一类',
    industry: '广电广播',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2025-06-01',
    endDate: '2026-12-01',
    daysRemaining: 97,
    unitName: '央台协同中心',
  },
  {
    id: 71,
    name: '南阳农业职业学院现代信息技术学院',
    status: '正式',
    location: '河南/南阳',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2025-09-08',
    endDate: '2026-09-08',
    daysRemaining: 13,
    unitName: '南阳农院单元',
  },
  {
    id: 72,
    name: '漯河市委网信办应急指挥科',
    status: '正式',
    location: '河南/漯河',
    category: '一类',
    industry: '网信部门',
    salesName: '李鹏飞',
    salesPhone: '187****8601',
    enabled: true,
    startDate: '2025-09-16',
    endDate: '2026-09-16',
    daysRemaining: 21,
    unitName: '漯河应急单元',
  },
  {
    id: 73,
    name: '同济大学智能网联汽车测评实验室',
    status: '试用',
    location: '上海/嘉定区',
    category: '三类',
    industry: '职校高校',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2026-08-06',
    endDate: '2026-09-20',
    daysRemaining: 25,
    unitName: '同济智车单元',
  },
  {
    id: 74,
    name: '周口市委网信办舆情监测中心',
    status: '正式',
    location: '河南/周口',
    category: '一类',
    industry: '网信部门',
    salesName: '李龙锐',
    salesPhone: '176****3418',
    enabled: true,
    startDate: '2025-09-30',
    endDate: '2026-09-30',
    daysRemaining: 35,
    unitName: '周口监测单元',
  },
  {
    id: 75,
    name: '南京医科大学第一附属医院信息处',
    status: '正式',
    location: '江苏/南京市',
    category: '二类',
    industry: '医疗健康',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2025-09-04',
    endDate: '2026-09-04',
    daysRemaining: 9,
    unitName: '南医大信息处',
  },
  {
    id: 76,
    name: '国网安徽省电力有限公司合肥供电公司',
    status: '试用',
    location: '安徽/合肥市',
    category: '二类',
    industry: '电力',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: true,
    startDate: '2026-08-14',
    endDate: '2026-09-28',
    daysRemaining: 33,
    unitName: '合肥供电单元',
  },
  {
    id: 77,
    name: '湖北省广播电视信息网络股份有限公司',
    status: '正式',
    location: '湖北/武汉市',
    category: '一类',
    industry: '广电广播',
    salesName: '廖伟',
    salesPhone: '189****4954',
    enabled: false,
    startDate: '2024-07-15',
    endDate: '2025-07-15',
    daysRemaining: 0,
    unitName: '湖北广电网络',
  },
  {
    id: 78,
    name: '惠州市大亚湾区融媒体中心',
    status: '试用',
    location: '广东/惠州市',
    category: '一类',
    industry: '媒体发布',
    salesName: '李学坚',
    salesPhone: '186****8245',
    enabled: true,
    startDate: '2026-08-16',
    endDate: '2026-09-16',
    daysRemaining: 21,
    unitName: '大亚湾融媒',
  },
  {
    id: 79,
    name: '齐鲁交通信息集团有限公司',
    status: '正式',
    location: '山东/济南市',
    category: '一类',
    industry: '交通运输',
    salesName: '孙浩',
    salesPhone: '136****9912',
    enabled: true,
    startDate: '2025-10-10',
    endDate: '2026-10-10',
    daysRemaining: 45,
    unitName: '齐鲁交通单元',
  },
  {
    id: 80,
    name: '中南大学湘雅二医院智慧医疗中心',
    status: '试用',
    location: '湖南/长沙市',
    category: '二类',
    industry: '医疗健康',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: true,
    startDate: '2026-08-26',
    endDate: '2026-09-26',
    daysRemaining: 31,
    unitName: '湘雅智慧单元',
  },
  {
    id: 81,
    name: '中共成都市锦江区委政法委员会',
    status: '试用',
    location: '四川/成都市',
    category: '一类',
    industry: '政务服务',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2026-08-08',
    endDate: '2026-09-08',
    daysRemaining: 13,
    unitName: '锦江政法单元',
  },
  {
    id: 82,
    name: '国网江西省电力公司抚州供电分公司',
    status: '正式',
    location: '江西/抚州市',
    category: '二类',
    industry: '电力',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: false,
    startDate: '2025-08-05',
    endDate: '2026-08-20',
    daysRemaining: 0,
    unitName: '抚州供电单元',
  },
  {
    id: 83,
    name: '泉州市金融投资集团数据运营部',
    status: '试用',
    location: '福建/泉州市',
    category: '一类',
    industry: '金融证券',
    salesName: '钱琳',
    salesPhone: '185****1290',
    enabled: true,
    startDate: '2026-08-18',
    endDate: '2026-09-30',
    daysRemaining: 35,
    unitName: '泉州金投单元',
  },
  {
    id: 84,
    name: '西北工业大学无人系统研究院',
    status: '试用',
    location: '陕西/西安市',
    category: '三类',
    industry: '职校高校',
    salesName: '郭凯',
    salesPhone: '166****9070',
    enabled: true,
    startDate: '2026-08-16',
    endDate: '2026-10-02',
    daysRemaining: 37,
    unitName: '西工大创研院',
  },
  {
    id: 85,
    name: '中共常州市委网络安全和信息化委员会办公室',
    status: '正式',
    location: '江苏/常州市',
    category: '一类',
    industry: '网信部门',
    salesName: '陈晨',
    salesPhone: '137****5521',
    enabled: true,
    startDate: '2025-11-25',
    endDate: '2026-11-25',
    daysRemaining: 91,
    unitName: '常州网信单元',
  },
  {
    id: 86,
    name: '安徽省教育网络安全应急响应中心',
    status: '试用',
    location: '安徽/合肥市',
    category: '二类',
    industry: '职校高校',
    salesName: '赵敏',
    salesPhone: '159****4433',
    enabled: false,
    startDate: '2026-08-05',
    endDate: '2026-09-05',
    daysRemaining: 10,
    unitName: '皖教安应中心',
  },
  {
    id: 87,
    name: '国网浙江省电力有限公司温州供电公司',
    status: '正式',
    location: '浙江/温州市',
    category: '二类',
    industry: '电力',
    salesName: '周小芳',
    salesPhone: '135****6677',
    enabled: true,
    startDate: '2025-07-20',
    endDate: '2026-09-15',
    daysRemaining: 20,
    unitName: '温州供电单元',
  },
  {
    id: 88,
    name: '天津北方网新媒体集团技术运维部',
    status: '试用',
    location: '天津/和平区',
    category: '一类',
    industry: '媒体发布',
    salesName: '王飞飞',
    salesPhone: '138****1122',
    enabled: true,
    startDate: '2026-08-22',
    endDate: '2026-09-22',
    daysRemaining: 27,
    unitName: '北方网运维组',
  },
  {
    id: 89,
    name: '中共成都市金牛区委网络安全和信息化委员会办公室',
    status: '正式',
    location: '四川/成都市',
    category: '一类',
    industry: '网信部门',
    salesName: '张云昭',
    salesPhone: '134****2732',
    enabled: true,
    startDate: '2025-05-10',
    endDate: '2027-05-10',
    daysRemaining: 257,
    unitName: '金牛网信单元',
  },
  {
    id: 90,
    name: '南昌航空大学通航产业数字化研究院',
    status: '试用',
    location: '江西/南昌市',
    category: '二类',
    industry: '职校高校',
    salesName: '张锐',
    salesPhone: '158****2653',
    enabled: true,
    startDate: '2026-08-08',
    endDate: '2026-09-22',
    daysRemaining: 27,
    unitName: '昌航通航单元',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'LOG-20260811-001',
    operator: '王飞飞',
    department: '产品二部',
    action: '新增机构',
    target: '中共佛山市委网络安全和信息化委员会办公室',
    ip: '192.168.1.104',
    time: '2026-08-11 17:42:10',
    status: '成功',
  },
  {
    id: 'LOG-20260811-002',
    operator: '王飞飞',
    department: '产品二部',
    action: '切换机构状态',
    target: '国网河南省电力公司商丘供电公司 (开启)',
    ip: '192.168.1.104',
    time: '2026-08-11 16:15:33',
    status: '成功',
  },
  {
    id: 'LOG-20260811-003',
    operator: '张伟',
    department: '运维组',
    action: '修改全局配置',
    target: '更新30天到期预警触发阀值',
    ip: '10.0.4.12',
    time: '2026-08-11 14:02:00',
    status: '成功',
  },
  {
    id: 'LOG-20260811-004',
    operator: '李娜',
    department: '销售二组',
    action: '编辑机构信息',
    target: '四川省公安厅 (更改销售联系人)',
    ip: '192.168.2.88',
    time: '2026-08-10 11:20:45',
    status: '成功',
  },
];
