import { SystemAccountUser, SystemLogItem } from '../../types';

export const initialSystemAccounts: SystemAccountUser[] = [
  {
    id: 'ACC-001',
    name: '王飞飞',
    username: 'wangfeifei',
    wechat: 'wangff_speed',
    gender: 'male',
    phone: '13812345678',
    email: 'wangfeifei@mediaspeed.com',
    dept: '产品二部',
    roleId: 'super_admin',
    roleName: '超级管理员',
    roleBadgeColor: 'bg-red-50 text-red-600 border-red-200',
    dataScope: 'all',
    dataScopeDesc: '全网所有机构与系统设置 (无限制)',
    status: 'active',
    mfaEnabled: true,
    ipWhitelist: '192.168.1.0/24, 10.0.0.0/8',
    lastLoginTime: '2026-08-27 18:30:12',
    lastLoginIp: '192.168.1.104',
    lastLoginLocation: '北京 海淀区',
    createdAt: '2025-01-10 09:00:00',
    permissions: [
      '机构全生命周期管理',
      '全局配置与阈值调度',
      '运营监控实时大屏',
      '系统账号与权限分发',
      '全量安全审计日志',
      '核心字典与模板编辑',
    ],
    remarks: '平台系统总架构师与产品二部负责人',
  },
  {
    id: 'ACC-002',
    name: '张伟',
    username: 'zhangwei',
    wechat: 'zhangwei_ops',
    gender: 'male',
    phone: '13987654321',
    email: 'zhangwei@mediaspeed.com',
    dept: '平台运维组',
    roleId: 'ops_admin',
    roleName: '平台运维主管',
    roleBadgeColor: 'bg-blue-50 text-blue-600 border-blue-200',
    dataScope: 'all',
    dataScopeDesc: '全网所有机构监控与节点运维',
    status: 'active',
    mfaEnabled: true,
    ipWhitelist: '10.0.4.0/24',
    lastLoginTime: '2026-08-27 17:15:20',
    lastLoginIp: '10.0.4.12',
    lastLoginLocation: '上海 浦东新区',
    createdAt: '2025-02-15 10:30:00',
    permissions: [
      '机构状态运维与开通',
      '全局到期与短信调度',
      '运营监控大屏与报表',
      '定时任务与运行日志',
    ],
    remarks: '负责全国云节点与高可用运维保障',
  },
  {
    id: 'ACC-003',
    name: '李娜',
    username: 'lina',
    wechat: 'lina_business',
    gender: 'female',
    phone: '13766668888',
    email: 'lina@mediaspeed.com',
    dept: '销售与商务二组',
    roleId: 'business_lead',
    roleName: '商务支持专家',
    roleBadgeColor: 'bg-purple-50 text-purple-600 border-purple-200',
    dataScope: 'formal_only',
    dataScopeDesc: '所属负责的正式与试用机构',
    status: 'active',
    mfaEnabled: false,
    lastLoginTime: '2026-08-27 15:42:11',
    lastLoginIp: '192.168.2.88',
    lastLoginLocation: '广东 广州市天河区',
    createdAt: '2025-03-01 14:00:00',
    permissions: [
      '机构录入与商机报备',
      '合同到期预警跟进',
      '配额查看与追加提报',
    ],
    remarks: '华南区商务签约与客户服务主跟进人',
  },
  {
    id: 'ACC-004',
    name: '郭凯',
    username: 'guokai',
    wechat: 'guokai_sales',
    gender: 'male',
    phone: '16612349070',
    email: 'guokai@mediaspeed.com',
    dept: '商务拓展部',
    roleId: 'sales_rep',
    roleName: '商务代表',
    roleBadgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    dataScope: 'regional',
    dataScopeDesc: '华中大区（河南/湖北）机构数据',
    status: 'active',
    mfaEnabled: false,
    lastLoginTime: '2026-08-27 11:20:05',
    lastLoginIp: '117.136.12.89',
    lastLoginLocation: '河南 郑州市金水区',
    createdAt: '2025-04-12 11:00:00',
    permissions: [
      '机构录入与信息查看',
      '试用延期申请提报',
    ],
    remarks: '河南电力系统及高校融媒项目代表',
  },
  {
    id: 'ACC-005',
    name: '赵子轩',
    username: 'zhaozx',
    wechat: 'zhaozx_sec',
    gender: 'male',
    phone: '15011223344',
    email: 'zhaozx@mediaspeed.com',
    dept: '安全合规部',
    roleId: 'audit_admin',
    roleName: '系统审计管理员',
    roleBadgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    dataScope: 'all',
    dataScopeDesc: '全平台日志与合规审计脱敏数据',
    status: 'active',
    mfaEnabled: true,
    ipWhitelist: '192.168.10.0/24',
    lastLoginTime: '2026-08-27 16:50:33',
    lastLoginIp: '192.168.10.22',
    lastLoginLocation: '北京 海淀区',
    createdAt: '2025-02-01 08:30:00',
    permissions: [
      '全量安全审计日志检索',
      '管理员操作追溯与取证',
      '等保三级日志归档与导出',
    ],
    remarks: '独立安全与合规审计专员',
  },
  {
    id: 'ACC-006',
    name: '陈晓琳',
    username: 'chenxl',
    wechat: 'chenxl_cfg',
    gender: 'female',
    phone: '18855443322',
    email: 'chenxl@mediaspeed.com',
    dept: '业务运营中心',
    roleId: 'config_admin',
    roleName: '机构配置专员',
    roleBadgeColor: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    dataScope: 'all',
    dataScopeDesc: '全机构业务规则、模板与打分模型',
    status: 'active',
    mfaEnabled: true,
    lastLoginTime: '2026-08-27 14:10:48',
    lastLoginIp: '192.168.1.115',
    lastLoginLocation: '北京 朝阳区',
    createdAt: '2025-05-18 15:20:00',
    permissions: [
      '报送模板与字段定制',
      '多级审核流程编排',
      '考核指标与打分规则配置',
      '数据字典分类维护',
    ],
    remarks: '负责新入驻政企机构业务流程梳理与初始化',
  },
  {
    id: 'ACC-007',
    name: '周明宇',
    username: 'zhoumy',
    jobNumber: 'MT-8007',
    gender: 'male',
    phone: '13599887766',
    email: 'zhoumy@mediaspeed.com',
    dept: '销售与商务一组',
    roleId: 'sales_rep',
    roleName: '商务代表',
    roleBadgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    dataScope: 'regional',
    dataScopeDesc: '西南大区（四川/重庆/贵州）机构数据',
    status: 'disabled',
    mfaEnabled: false,
    lastLoginTime: '2026-08-15 10:00:00',
    lastLoginIp: '222.209.18.55',
    lastLoginLocation: '四川 成都市武侯区',
    createdAt: '2025-06-01 09:30:00',
    permissions: ['机构录入与信息查看'],
    remarks: '因岗位交接已临时冻结账号权限',
  },
  {
    id: 'ACC-008',
    name: '韩雪',
    username: 'hanxue',
    jobNumber: 'MT-8008',
    gender: 'female',
    phone: '17722334455',
    email: 'hanxue@mediaspeed.com',
    dept: '平台运维组',
    roleId: 'ops_admin',
    roleName: '平台运维主管',
    roleBadgeColor: 'bg-blue-50 text-blue-600 border-blue-200',
    dataScope: 'all',
    dataScopeDesc: '全国网格节点监控与网络健康巡检',
    status: 'active',
    mfaEnabled: true,
    lastLoginTime: '2026-08-27 09:05:40',
    lastLoginIp: '10.0.4.15',
    lastLoginLocation: '上海 浦东新区',
    createdAt: '2025-07-20 13:40:00',
    permissions: [
      '运营监控实时大屏',
      '服务异常日志抓取',
      '报警渠道与网关维护',
    ],
    remarks: '负责夜班巡检与基础设施稳定性保障',
  },
];

export const initialSystemLogs: SystemLogItem[] = [
  // ================= 1. 登录日志 (Login Logs) =================
  {
    id: 'LOG-20260827-101',
    category: 'login',
    operator: '王飞飞',
    operatorUsername: 'wangfeifei',
    operatorJobNo: 'MT-8001',
    department: '产品二部',
    role: '超级管理员',
    action: '账号登录 (MFA双因子核验)',
    module: '安全认证中心',
    target: '管理后台 Web 端 (动态令牌验证通过)',
    targetId: 'AUTH-SESSION-8842',
    ip: '192.168.1.104',
    location: '北京 海淀区 (办公内网)',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 18:30:12',
    status: '成功',
    durationMs: 110,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login-mfa',
    responseSummary: '身份认证成功，会话有效时长 8 小时，颁发 JWT 令牌',
  },
  {
    id: 'LOG-20260827-102',
    category: 'login',
    operator: '张伟',
    operatorUsername: 'zhangwei',
    operatorJobNo: 'MT-8002',
    department: '平台运维组',
    role: '平台运维主管',
    action: '企微单点登录 (SSO)',
    module: '安全认证中心',
    target: '管理后台 Web 端 (企业微信扫码授权)',
    targetId: 'AUTH-SESSION-8830',
    ip: '10.0.4.12',
    location: '上海 浦东新区 (运维专线)',
    browser: 'Edge 126.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 17:15:20',
    status: '成功',
    durationMs: 85,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/sso/qywechat',
    responseSummary: '企业微信单点登录验证成功，自动同步部门角色权限',
  },
  {
    id: 'LOG-20260827-103',
    category: 'login',
    operator: '赵子轩',
    operatorUsername: 'zhaozx',
    operatorJobNo: 'MT-8005',
    department: '安全合规部',
    role: '系统审计管理员',
    action: '账号登录 (白名单IP校验)',
    module: '安全认证中心',
    target: '管理后台 Web 端 (安全内网专线接入)',
    targetId: 'AUTH-SESSION-8815',
    ip: '192.168.10.22',
    location: '北京 海淀区 (合规内网)',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 16:50:33',
    status: '成功',
    durationMs: 95,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login',
    responseSummary: '独立审计通道校验通过，IP 白名单验证无误',
  },
  {
    id: 'LOG-20260827-104',
    category: 'login',
    operator: '外部未知IP',
    operatorUsername: 'admin_test',
    department: '外部访客',
    role: '未授权访客',
    action: '异地密码暴力尝试登录',
    module: '安全风控网关',
    target: '非法尝试爆破管理后台接口，连续输错 5 次',
    targetId: 'BLOCK-IP-991',
    ip: '218.77.130.45',
    location: '未知外网节点 (湖南 长沙市/高危)',
    browser: 'Python-Requests/2.31',
    os: 'Linux x86_64',
    time: '2026-08-27 16:55:01',
    status: '拦截',
    durationMs: 5,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login',
    errorCode: 'SEC_ERR_IP_BLACKLISTED',
    errorMessage: '触发防暴力破解高危规则，IP 已自动加入临时封禁黑名单 24 小时',
  },
  {
    id: 'LOG-20260827-105',
    category: 'login',
    operator: '李娜',
    operatorUsername: 'lina',
    operatorJobNo: 'MT-8003',
    department: '销售与商务二组',
    role: '商务支持专家',
    action: '账号登录 (密码验证)',
    module: '安全认证中心',
    target: '管理后台 Web 端',
    targetId: 'AUTH-SESSION-8790',
    ip: '192.168.2.88',
    location: '广东 广州市天河区',
    browser: 'Safari 18.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 15:42:11',
    status: '成功',
    durationMs: 78,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login',
    responseSummary: '密码认证成功，开启华南区商务会话',
  },
  {
    id: 'LOG-20260827-106',
    category: 'login',
    operator: '郭凯',
    operatorUsername: 'guokai',
    operatorJobNo: 'MT-8004',
    department: '商务拓展部',
    role: '商务代表',
    action: '异地基站登录 (二次核验)',
    module: '安全风控网关',
    target: '由郑州移动4G网络登录，短信二次验证通过',
    targetId: 'AUTH-SESSION-8799',
    ip: '117.136.12.89',
    location: '河南 郑州市金水区',
    browser: 'Chrome Mobile 126.0',
    os: 'Android 14',
    time: '2026-08-27 11:20:05',
    status: '警告',
    durationMs: 140,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login-sms',
    responseSummary: '异地基站登录，已记录设备硬件指纹并完成短信验证码核身',
  },
  {
    id: 'LOG-20260827-107',
    category: 'login',
    operator: '陈晓琳',
    operatorUsername: 'chenxl',
    operatorJobNo: 'MT-8006',
    department: '业务运营中心',
    role: '机构配置专员',
    action: '账号登出 (注销会话)',
    module: '安全认证中心',
    target: '管理后台 Web 端 (主动退出)',
    targetId: 'AUTH-SESSION-8710',
    ip: '192.168.1.115',
    location: '北京 朝阳区',
    browser: 'Chrome 127.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 18:02:10',
    status: '成功',
    durationMs: 15,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/logout',
    responseSummary: '用户主动登出，安全清除 Token 与 Redis 会话缓存',
  },
  {
    id: 'LOG-20260827-108',
    category: 'login',
    operator: '韩雪',
    operatorUsername: 'hanxue',
    operatorJobNo: 'MT-8008',
    department: '平台运维组',
    role: '平台运维主管',
    action: '账号登录 (密码验证)',
    module: '安全认证中心',
    target: '管理后台 Web 端',
    targetId: 'AUTH-SESSION-8650',
    ip: '10.0.4.15',
    location: '上海 浦东新区 (运维专线)',
    browser: 'Chrome 128.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 09:05:40',
    status: '成功',
    durationMs: 60,
    httpMethod: 'POST',
    apiUrl: '/api/v2/auth/login',
    responseSummary: '早班巡检登录成功',
  },

  // ================= 2. 操作日志 (Operation Logs) =================
  {
    id: 'OP-20260827-001',
    category: 'audit',
    operator: '王飞飞',
    operatorUsername: 'wangfeifei',
    operatorJobNo: 'MT-8001',
    department: '产品二部',
    role: '超级管理员',
    action: '开通并激活机构服务',
    module: '机构管理',
    target: '随州市网信中心 (由试用转为正式服务，年限 +365天)',
    targetId: 'INST-05',
    ip: '192.168.1.104',
    location: '北京 海淀区',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 18:42:15',
    status: '成功',
    durationMs: 38,
    httpMethod: 'POST',
    apiUrl: '/api/v2/institutions/5/provision',
    requestPayload: {
      institutionId: 5,
      newStatus: '正式',
      extensionDays: 365,
      quotaQrCode: 100,
      assignedSales: '廖伟',
    },
    beforeChange: { status: '试用', isExpired: true, daysRemaining: 0 },
    afterChange: { status: '正式', isExpired: false, daysRemaining: 365 },
  },
  {
    id: 'OP-20260827-002',
    category: 'audit',
    operator: '陈晓琳',
    operatorUsername: 'chenxl',
    operatorJobNo: 'MT-8006',
    department: '业务运营中心',
    role: '机构配置专员',
    action: '更新审核打分模型与维度',
    module: '业务规则配置',
    target: '中共佛山市委网信办 - 2026年度突发舆情速报评分规则 (基准分 75分)',
    targetId: 'RULE-GRP-01',
    ip: '192.168.1.115',
    location: '北京 朝阳区',
    browser: 'Chrome 127.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 17:30:28',
    status: '成功',
    durationMs: 45,
    httpMethod: 'PUT',
    apiUrl: '/api/v2/institutions/4/scoring-rules',
    requestPayload: {
      ruleGroupId: 'score-foshan-01',
      passScore: 75,
      excellentScore: 92,
      zeroToleranceViolation: true,
    },
    beforeChange: { passScore: 60, excellentScore: 85 },
    afterChange: { passScore: 75, excellentScore: 92 },
  },
  {
    id: 'OP-20260827-003',
    category: 'audit',
    operator: '张伟',
    operatorUsername: 'zhangwei',
    operatorJobNo: 'MT-8002',
    department: '平台运维组',
    role: '平台运维主管',
    action: '调整全局到期预警触发阈值',
    module: '全局配置',
    target: '将服务到期预警天数由 15 天调整为 30 天',
    targetId: 'CFG-NOTICE-01',
    ip: '10.0.4.12',
    location: '上海 浦东新区',
    browser: 'Edge 126.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 16:15:10',
    status: '成功',
    durationMs: 22,
    httpMethod: 'PATCH',
    apiUrl: '/api/v2/system/config/global',
    requestPayload: {
      noticeDays: 30,
      autoDisableExpired: true,
      smsNotification: true,
    },
    beforeChange: { noticeDays: 15 },
    afterChange: { noticeDays: 30 },
  },
  {
    id: 'OP-20260827-004',
    category: 'audit',
    operator: '赵子轩',
    operatorUsername: 'zhaozx',
    operatorJobNo: 'MT-8005',
    department: '安全合规部',
    role: '系统审计管理员',
    action: '敏感审计日志脱敏导出',
    module: '系统日志',
    target: '导出 2026-08-20 至 08-26 审计日志数据包 (含动态溯源水印)',
    targetId: 'EXPORT-LOG-772',
    ip: '192.168.10.22',
    location: '北京 海淀区 (合规内网)',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 16:50:33',
    status: '成功',
    durationMs: 320,
    httpMethod: 'POST',
    apiUrl: '/api/v2/audit/export',
    responseSummary: '导出 1,480 条加密日志，文件哈希 SHA-256 校验通过',
  },
  {
    id: 'OP-20260827-005',
    category: 'audit',
    operator: '陈晓琳',
    operatorUsername: 'chenxl',
    operatorJobNo: 'MT-8006',
    department: '业务运营中心',
    role: '机构配置专员',
    action: '更新报送模版字段结构',
    module: '业务规则配置',
    target: '模版【突发紧急事件一键速报表单】增加「涉事位置GPS坐标」必填字段',
    targetId: 'TMPL-001',
    ip: '192.168.1.115',
    location: '北京 朝阳区',
    browser: 'Chrome 127.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 15:10:00',
    status: '成功',
    durationMs: 50,
    beforeChange: {
      templateName: '突发紧急事件一键速报表单',
      fieldCount: 7,
      hasGpsField: false,
    },
    afterChange: {
      templateName: '突发紧急事件一键速报表单',
      fieldCount: 8,
      hasGpsField: true,
      newField: { name: '涉事位置GPS坐标', type: 'location', required: true },
    },
  },
  {
    id: 'OP-20260827-006',
    category: 'audit',
    operator: '王飞飞',
    operatorUsername: 'wangfeifei',
    operatorJobNo: 'MT-8001',
    department: '产品二部',
    role: '超级管理员',
    action: '机构二维码配额追加',
    module: '机构管理',
    target: '国网商丘供电公司：配额由 50 个扩容至 100 个',
    targetId: 'QUOTA-INST-01',
    ip: '192.168.1.104',
    location: '北京 海淀区',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 14:40:12',
    status: '成功',
    durationMs: 30,
    beforeChange: { totalLimit: 50, usedCount: 18, remaining: 32 },
    afterChange: { totalLimit: 100, usedCount: 18, remaining: 82 },
  },
  {
    id: 'OP-20260827-007',
    category: 'audit',
    operator: '李娜',
    operatorUsername: 'lina',
    operatorJobNo: 'MT-8003',
    department: '销售与商务二组',
    role: '商务支持专家',
    action: '录入新接入机构信息',
    module: '机构管理',
    target: '中共峡江县委宣传部 (一类/正式/江西吉安)',
    targetId: 'INST-03',
    ip: '192.168.2.88',
    location: '广东 广州市',
    browser: 'Safari 18.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 14:08:44',
    status: '成功',
    durationMs: 62,
    httpMethod: 'POST',
    apiUrl: '/api/v2/institutions/create',
    requestPayload: {
      name: '中共峡江县委宣传部',
      industry: '网信部门',
      region: '江西/吉安市/峡江县',
      salesName: '张锐',
    },
  },
  {
    id: 'OP-20260827-008',
    category: 'audit',
    operator: '陈晓琳',
    operatorUsername: 'chenxl',
    operatorJobNo: 'MT-8006',
    department: '业务运营中心',
    role: '机构配置专员',
    action: '更新数据字典项',
    module: '业务规则配置',
    target: '舆情严重等级字典新增「特级重大舆情(I级)」',
    targetId: 'DICT-LEVEL-09',
    ip: '192.168.1.115',
    location: '北京 朝阳区',
    browser: 'Chrome 127.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 11:45:00',
    status: '成功',
    durationMs: 18,
    beforeChange: { dictType: 'emergency_level', count: 4 },
    afterChange: { dictType: 'emergency_level', count: 5, added: 'I级(特大)' },
  },
  {
    id: 'OP-20260827-009',
    category: 'audit',
    operator: '王飞飞',
    operatorUsername: 'wangfeifei',
    operatorJobNo: 'MT-8001',
    department: '产品二部',
    role: '超级管理员',
    action: '停用风险管理员账号',
    module: '系统管理/账号管理',
    target: '账号周明宇 (zhoumy / MT-8007)',
    targetId: 'ACC-007',
    ip: '192.168.1.104',
    location: '北京 海淀区',
    browser: 'Chrome 128.0 (macOS)',
    os: 'macOS 15.0',
    time: '2026-08-27 10:20:19',
    status: '成功',
    durationMs: 19,
    httpMethod: 'PUT',
    apiUrl: '/api/v2/system/users/ACC-007/status',
    requestPayload: { status: 'disabled', reason: '岗位调动交接，权限冻结' },
    beforeChange: { status: 'active' },
    afterChange: { status: 'disabled' },
  },
  {
    id: 'OP-20260827-010',
    category: 'audit',
    operator: '张伟',
    operatorUsername: 'zhangwei',
    operatorJobNo: 'MT-8002',
    department: '平台运维组',
    role: '平台运维主管',
    action: '手动执行全量服务到期扫描与提醒',
    module: '全局配置/运维调度',
    target: '全量扫描 18 家正式与试用机构，触发 2 家到期待续约机构短信通知',
    targetId: 'JOB-EXPIRY-BATCH',
    ip: '10.0.4.12',
    location: '上海 浦东新区',
    browser: 'Edge 126.0 (Windows 11)',
    os: 'Windows 11 x64',
    time: '2026-08-27 08:30:00',
    status: '成功',
    durationMs: 240,
    httpMethod: 'POST',
    apiUrl: '/api/v2/system/jobs/run-expiry-scan',
    responseSummary: '任务执行完毕，成功发送 2 条短信提醒',
  },
];

export const systemRoleOptions = [
  {
    id: 'super_admin',
    name: '超级管理员',
    color: 'bg-red-50 text-red-600 border-red-200',
    description: '拥有系统所有功能模块与全部机构的最高管理配置与账号审计权限。',
  },
  {
    id: 'ops_admin',
    name: '平台运维主管',
    color: 'bg-blue-50 text-blue-600 border-blue-200',
    description: '负责平台所有机构开通、服务运维、全局阈值配置与系统监控大屏。',
  },
  {
    id: 'config_admin',
    name: '机构配置专员',
    color: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    description: '负责业务模版、审核打分模型、指标公式及数据字典的维护调优。',
  },
  {
    id: 'audit_admin',
    name: '系统审计管理员',
    color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    description: '独立负责安全合规审计、管理员行为轨迹追溯与等保日志导出。',
  },
  {
    id: 'business_lead',
    name: '商务支持专家',
    color: 'bg-purple-50 text-purple-600 border-purple-200',
    description: '负责重点政企客户机构建档、合同生命周期跟进与配额追加提报。',
  },
  {
    id: 'sales_rep',
    name: '商务代表',
    color: 'bg-amber-50 text-amber-700 border-amber-200',
    description: '负责指定区域范围内的机构客户录入与日常客户沟通对接。',
  },
];

export const systemDepartmentOptions = [
  '产品二部',
  '平台运维组',
  '业务运营中心',
  '安全合规部',
  '销售与商务一组',
  '销售与商务二组',
  '商务拓展部',
];
